version: '3.7'

services:
  api:
    build: .
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    ports:
      - 8000:8000
    depends_on:
      - db
      - agent
      - celery
      - redis
    environment: &api-environment
      DJANGO_ENV: dev
      DJANGO_SECRET_KEY: secret_key
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      EMAIL_HOST: smtp.yandex.ru
      EMAIL_HOST_USER: tema052008
      EMAIL_HOST_PASSWORD: gfkeebivkoebpiza
      EMAIL_PORT: 465
      EMAIL_USE_TLS: "False"
      EMAIL_USE_SSL: "True"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:11.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  agent:
    container_name: newrelic-infra
    image: newrelic/infrastructure:latest
    cap_add:
      - SYS_PTRACE
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - "/:/localhost:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      NRIA_LICENSE_KEY: eu01xxf50860d50d2c3cf38b2cebccf322beNRAL

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery --app=task_manager worker --loglevel=info
    environment:
      <<: *api-environment
    volumes:
      - .:/app
    depends_on:
      - redis