# Generated by Django 4.1.7 on 2023-03-08 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_tag_user_role_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="mod_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("new_task", "New Task"),
                    ("in_development", "In Development"),
                    ("in_qa", "In Qa"),
                    ("in_code_review", "In Code Review"),
                    ("ready_for_release", "Ready For Release"),
                    ("released", "Released"),
                    ("archived", "Archived"),
                ],
                default="new_task",
                max_length=255,
                null=True,
            ),
        ),
    ]
