# Generated by Django 4.1.7 on 2023-03-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_tag_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="task",
        ),
        migrations.AddField(
            model_name="task",
            name="tag",
            field=models.ManyToManyField(to="main.tag"),
        ),
    ]
