# Generated by Django 4.1.7 on 2023-03-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_rename_tag_task_tags_alter_user_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
