# Generated by Django 4.1.7 on 2023-04-05 06:10

from django.db import migrations, models
import main.services.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_task_author_alter_task_executor"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_picture",
            field=models.ImageField(
                null=True,
                storage=main.services.storage_backends.public_storage,
                upload_to="",
            ),
        ),
    ]
