name: Main

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        env:
          COVERAGE: true
          RAILS_ENV: test
        run: docker-compose --file docker-compose.ci.yml run --rm api pytest
      - name: Coveralls GitHub Action
        env:
            COVERALLS_REPO_TOKEN: Hhrmka88MFEloasrclabav4xhEkdvOBMD
        run: docker-compose --file docker-compose.ci.yml run --rm api coveralls
   
